[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "regobs_evo_comp"
version = "0.1.0"
description = "RegObs EVO computation tools"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "snowpacktools @ git+https://gitlab.com/rasmetikus/snowpacktools.git@feature/regobs_evo",
    "regobslib",
    "matplotlib"
]

[tool.setuptools.packages.find]
where = ["src"]

